env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:vue/vue3-essential
  - prettier
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - vue
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - 0
  quotes:
    - error
    - single
  semi:
    - error
    - never
  vue/multi-word-component-names:
    - 0
